// GÉNÉRÉ par tools/generate-accounts.ts — ne pas modifier à la main.
// SERVEUR UNIQUEMENT : importé par app/api/setup/route.ts. Ce sont les
// mots de passe PAR DÉFAUT (déjà listés dans docs/COMPTES.md) ; chacun
// est invité à changer le sien à la première connexion.

export interface SeedAccount {
  user: string;
  name: string;
  password: string;
}

export const SEED_ACCOUNTS: SeedAccount[] = [
  { user: "abdel", name: "Abdel", password: "pivot92" },
  { user: "adel", name: "Adel", password: "sprint74" },
  { user: "adil", name: "Adil", password: "gardien72" },
  { user: "adilm", name: "Adil Maimouni", password: "ballon35" },
  { user: "adilz", name: "Adil Zerhoui", password: "praline56" },
  { user: "adrien", name: "Adrien", password: "pointu49" },
  { user: "aghiless", name: "Aghiless", password: "cage70" },
  { user: "anas", name: "Anas", password: "capitaine21" },
  { user: "anis", name: "Anis", password: "sombrero31" },
  { user: "anisr", name: "Anis R", password: "duel62" },
  { user: "ariless", name: "Ariless", password: "duel64" },
  { user: "ayman", name: "Ayman", password: "praline27" },
  { user: "azzedine", name: "Azzedine", password: "gardien54" },
  { user: "badis", name: "Badis", password: "duel49" },
  { user: "bilal", name: "Bilal", password: "cage45" },
  { user: "farid", name: "Farid", password: "arret86" },
  { user: "franz", name: "Franz", password: "maillot84" },
  { user: "gail", name: "Gaïl", password: "arret88" },
  { user: "giovani", name: "Giovani", password: "pointu53" },
  { user: "guillaume", name: "Guillaume", password: "passe36" },
  { user: "hasbi", name: "Hasbi", password: "sprint59" },
  { user: "hassana", name: "Hassan Abdel", password: "louche45" },
  { user: "henri", name: "Henri", password: "volee96" },
  { user: "houssyne", name: "Houssyne", password: "gardien53" },
  { user: "ibrahim", name: "Ibrahim", password: "roulette63" },
  { user: "ilies", name: "Ilies", password: "sifflet38" },
  { user: "illiasse", name: "illiasse", password: "terrain20" },
  { user: "ilyes", name: "Ilyes", password: "tacle17" },
  { user: "isma", name: "Isma", password: "gardien45" },
  { user: "jouneid", name: "Jouneid", password: "volee42" },
  { user: "k2r", name: "K2R", password: "cage68" },
  { user: "kader", name: "Kader", password: "louche53" },
  { user: "kais", name: "Kais", password: "sombrero40" },
  { user: "kamil", name: "Kamil", password: "buteur22" },
  { user: "kevinb", name: "Kevin B", password: "passe29" },
  { user: "kevinr", name: "kevin Raes", password: "sombrero17" },
  { user: "khadim", name: "Khadim", password: "duel43" },
  { user: "kylian", name: "Kylian", password: "maillot97" },
  { user: "lyesk", name: "Lyes Korogli", password: "terrain94" },
  { user: "malik", name: "Malik", password: "praline39" },
  { user: "marwan", name: "Marwan", password: "buteur33" },
  { user: "mehdi", name: "Mehdi", password: "volee18" },
  { user: "miken", name: "Miken", password: "buteur24" },
  { user: "moussa", name: "Moussa", password: "louche76" },
  { user: "moustapha", name: "Moustapha", password: "ballon59" },
  { user: "naim", name: "Naim", password: "louche82" },
  { user: "omar", name: "Omar", password: "ballon29" },
  { user: "rezki", name: "Rezki", password: "corner17" },
  { user: "ryad", name: "Ryad", password: "sifflet90" },
  { user: "sabri", name: "Sabri", password: "59Sabrii!" },
  { user: "samid", name: "Sami D", password: "sprint57" },
  { user: "samy", name: "Samy", password: "buteur28" },
  { user: "sebovic", name: "Sebovic", password: "crampon95" },
  { user: "selim", name: "Selim", password: "duel33" },
  { user: "seliml", name: "Selim laouadi", password: "buteur22" },
  { user: "sidali", name: "Sidali", password: "maillot52" },
  { user: "simonr", name: "Simon Ribeiro", password: "louche25" },
  { user: "smail", name: "Smail", password: "louche97" },
  { user: "soffiane", name: "Soffiane", password: "cage25" },
  { user: "sofiane", name: "Sofiane", password: "capitaine41" },
  { user: "sossoa", name: "Sosso Abdel", password: "sifflet98" },
  { user: "sossoc", name: "Sosso Coach", password: "sombrero18" },
  { user: "souley", name: "Souley", password: "roulette89" },
  { user: "wadie", name: "Wadie", password: "reprise55" },
  { user: "yacine", name: "Yacine", password: "passe34" },
  { user: "yacineb", name: "Yacine Ben", password: "sprint70" },
  { user: "yamin", name: "Yamin", password: "louche85" },
  { user: "yanis", name: "Yanis", password: "terrain43" },
  { user: "yassir", name: "Yassir", password: "corner85" },
  { user: "yazid", name: "Yazid", password: "arret99" },
  { user: "zakaria", name: "Zakaria", password: "duel80" },
  { user: "zakary", name: "Zakary", password: "sombrero93" },
  { user: "ziad", name: "Ziad", password: "sifflet71" },
];
