// Seed de démonstration — historique J1→J5 rejoué depuis refonte_STATS.xlsx.
// Sert de données initiales à la maquette Admin ; le moteur (engine.ts) en
// dérive classements, journées, cartes boost et alertes. À terme ce seed sera
// remplacé par la lecture Supabase — seul le store (store.ts) changera.

import type { JourneeMeta, MatchEntry, RosterEntry } from "./types";

export const SEED_JOURNEES: JourneeMeta[] = [
  { j: 1, date: "21 juin", sflTime: true },
  { j: 2, date: "28 juin", sflTime: false },
  { j: 3, date: "5 juil.", sflTime: false },
  { j: 4, date: "12 juil.", sflTime: false },
  { j: 5, date: "19 juil.", sflTime: false },
  { j: 6, date: "26 juil.", sflTime: false },
  { j: 7, date: "2 août", sflTime: false },
  { j: 8, date: "9 août", sflTime: false },
];

export const SEED_ROSTER: RosterEntry[] = [
  // Roster synchronisé sur JOUEURS & RÈGLES du classeur (joueurs sans match
  // compris). Hugo et Chouaib exclus à la demande de l'admin bien que le
  // classeur liste encore leurs lignes.
  { name: "Adil", poste: "MDC", profil: "Actif", base: [77, 75, 72, 70, 77, 83] },
  { name: "Anis", poste: "DC", profil: "Actif", base: [72, 77, 71, 72, 80, 83] },
  { name: "Ariless", poste: "MC/AT", profil: "Blessure", base: [77, 82, 88, 89, 81, 79] },
  { name: "Ayman", poste: "DD", profil: "Actif", base: [74, 73, 75, 74, 77, 80] },
  { name: "Azzedine", poste: "DG", profil: "Actif", base: [68, 67, 67, 65, 69, 72] },
  { name: "Badis", poste: "MC/MDC", profil: "Actif", base: [77, 76, 75, 78, 88, 90] },
  { name: "Franz", poste: "MDC/MC", profil: "Actif", base: [76, 80, 77, 74, 83, 80] },
  { name: "Ilies", poste: "AD", profil: "Actif", base: [84, 82, 83, 88, 77, 80] },
  { name: "Ilyes", poste: "MC/AT", profil: "Actif", base: [81, 85, 86, 90, 72, 66] },
  { name: "Ibrahim", poste: "DC", profil: "Actif", base: [72, 80, 79, 76, 83, 81] },
  { name: "Kader", poste: "MC/AT", profil: "Actif", base: [78, 78, 79, 84, 80, 82] },
  { name: "Marwan", poste: "MDC/MC", profil: "Actif", base: [76, 79, 78, 77, 82, 82] },
  { name: "Mehdi", poste: "MDC", profil: "Actif", base: [74, 73, 75, 76, 83, 88] },
  { name: "Moussa", poste: "DC/MDC", profil: "Actif", base: [77, 84, 75, 72, 89, 89] },
  { name: "Naim", poste: "DC", profil: "Actif", base: [65, 73, 78, 77, 76, 63] },
  { name: "Omar", poste: "MC", profil: "Actif", base: [81, 79, 85, 88, 72, 64] },
  { name: "Rezki", poste: "MDC", profil: "Actif", base: [75, 77, 76, 75, 85, 79] },
  { name: "Ryad", poste: "MC", profil: "Actif", base: [77, 80, 79, 81, 77, 78] },
  { name: "Sidali", poste: "MC/AG", profil: "Actif", base: [78, 77, 82, 85, 82, 77] },
  { name: "Smail", poste: "MC/MDC", profil: "Actif", base: [76, 75, 76, 78, 87, 88] },
  { name: "Sofiane", poste: "AT", profil: "Actif", base: [82, 81, 75, 77, 79, 80] },
  { name: "Souley", poste: "AT", profil: "Actif", base: [78, 80, 84, 86, 86, 91] },
  // « Wadie » : orthographe désormais utilisée par la feuille de match (ex-« Wadi »).
  { name: "Wadie", poste: "AT", profil: "Actif", base: [86, 80, 80, 78, 80, 80] },
  { name: "Yacine", poste: "MC/AT", profil: "Actif", base: [79, 80, 83, 83, 79, 79] },
  { name: "Yamin", poste: "MC/MDC", profil: "Actif", base: [85, 80, 82, 78, 80, 83] },
  { name: "Yanis", poste: "MC/MDC", profil: "Actif", base: [73, 74, 77, 77, 79, 78] },
  { name: "Hasbi", poste: "G", profil: "Actif", base: [85, 79, 79, 86, 92, 88] },
  { name: "Zakary", poste: "MC", profil: "Actif", base: [73, 83, 83, 80, 88, 85] },
  { name: "Soffiane", poste: "AT", profil: "Actif", base: [80, 83, 84, 85, 77, 76] },
  { name: "Bilal", poste: "MC", profil: "Actif", base: [76, 77, 74, 78, 78, 77] },
  { name: "Zakaria", poste: "MC", profil: "Actif", base: [77, 78, 77, 79, 76, 77] },
  { name: "Kylian", poste: "MC", profil: "Actif", base: [86, 82, 86, 84, 75, 80] },
  { name: "Adrien", poste: "DD", profil: "Actif", base: [76, 71, 73, 73, 78, 88] },
  { name: "Houssyne", poste: "G", profil: "Actif", base: null },
  { name: "Adil Zerhoui", poste: "MD", profil: "Actif", base: [79, 75, 77, 78, 84, 93] },
  { name: "Kamil", poste: "MC", profil: "Actif", base: [82, 78, 75, 79, 82, 91] },
  { name: "Hassan Abdel", poste: "MC", profil: "Actif", base: null },
  { name: "Sosso Abdel", poste: "DC", profil: "Actif", base: [79, 79, 85, 86, 86, 79] },
  { name: "Anas", poste: "MDC", profil: "Actif", base: [82, 77, 78, 80, 84, 85] },
  { name: "Samy", poste: "MC", profil: "Actif", base: [76, 77, 79, 78, 79, 80] },
  { name: "Kais", poste: "DD", profil: "Actif", base: [81, 77, 78, 77, 80, 74] },
  { name: "Adil Maimouni", poste: "DC", profil: "Actif", base: [75, 78, 83, 78, 77, 79] },
  { name: "Jouneid", poste: "MC", profil: "Actif", base: [85, 86, 92, 83, 82, 85] },
  { name: "Selim laouadi", poste: "MC", profil: "Actif", base: [69, 83, 86, 87, 77, 72] },
  { name: "Farid", poste: "DG", profil: "Actif", base: [77, 73, 74, 75, 79, 81] },
  { name: "Abdel", poste: "MC", profil: "Actif", base: [76, 80, 79, 79, 80, 79] },
  { name: "Moustapha", poste: "DG", profil: "Actif", base: [76, 77, 78, 73, 78, 75] },
  { name: "Selim", poste: null, profil: "Actif", base: null },
  { name: "Ziad", poste: "MDC", profil: "Actif", base: null },
  { name: "Khadim", poste: "MDC", profil: "Actif", base: null },
  { name: "Guillaume", poste: "DG", profil: "Actif", base: null },
  { name: "Sosso Coach", poste: "AT/BU", profil: "Actif", base: [87, 82, 83, 83, 88, 81] },
  { name: "Yacine Ben", poste: "DD", profil: "Actif", base: [72, 68, 69, 73, 77, 80] },
  { name: "Lyes Korogli", poste: "AG/MC", profil: "Actif", base: null },
  { name: "K2R", poste: "MC", profil: "Actif", base: [78, 77, 77, 76, 79, 77] },
  { name: "Gaïl", poste: "MDC", profil: "Actif", base: [79, 76, 77, 75, 78, 80] },
  { name: "Yazid", poste: null, profil: "Actif", base: null },
  { name: "Henri", poste: null, profil: "Actif", base: null },
  { name: "Isma", poste: null, profil: "Actif", base: null },
  { name: "Malik", poste: null, profil: "Actif", base: null },
  { name: "illiasse", poste: null, profil: "Actif", base: null },
  { name: "Giovani", poste: null, profil: "Actif", base: null },
  { name: "Aghiless", poste: null, profil: "Actif", base: null },
  { name: "Simon Ribeiro", poste: "MC", profil: "Actif", base: [80, 84, 88, 84, 86, 79] },
  { name: "kevin Raes", poste: null, profil: "Actif", base: null },
  { name: "Sebovic", poste: null, profil: "Actif", base: null },
  // Arrivé en J8 — non encore évalué.
  { name: "Yassir", poste: null, profil: "Actif", base: null },
  { name: "Adel", poste: null, profil: "Actif", base: null },
  { name: "Kevin B", poste: null, profil: "En attente", base: null },
  { name: "Anis R", poste: null, profil: "En attente", base: null },
  { name: "Sami D", poste: null, profil: "En attente", base: null },
  // Ajouté à la demande de l'admin. Base de départ à 75 partout (la valeur des
  // joueurs pas encore évalués) : elle suffit à lui donner une carte et une
  // place dans les classements, en attendant sa première journée.
  { name: "Sabri", poste: null, profil: "Actif", base: [75, 75, 75, 75, 75, 75] },
];

export const SEED_ENTRIES: MatchEntry[] = [
  // Regénéré intégralement depuis SFL_0908.xlsx (SAISIE MATCH) — le classeur
  // est la source de vérité. Équipes lues dans les couleurs de fond ; lignes
  // XTRATIME d'équipe agrégées en teamScoreBonus ; bloc « Xtratime » individuel
  // (bonus cumulés des prolongations J2→J7) importé en entrées extraTime avec
  // pepiteBonus : les points comptent, ni la présence, ni les matchs, ni les
  // stats — consigne explicite de l'admin. Équipes A/B de la J1 préservées ;
  // lignes de Hugo et Chouaib (retirés de l'app) sautées volontairement.
  // Chaque ligne recoupée avec « PP du match », chaque total avec CLASSEMENTS.
  { j: 1, player: "Badis", team: "Équipe A", statut: "Présent", result: "Victoire", sflTime: true, buts: 1, passes: 1, cleanSheet: false, mvp: false, impact: true, def: false, retard: false },
  { j: 1, player: "Ilyes", team: "Équipe A", statut: "Présent", result: "Victoire", sflTime: true, buts: 4, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 1, player: "Smail", team: "Équipe A", statut: "Présent", result: "Victoire", sflTime: true, buts: 2, passes: 2, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 1, player: "Naim", team: "Équipe A", statut: "Présent", result: "Victoire", sflTime: true, buts: 1, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 1, player: "Omar", team: "Équipe A", statut: "Présent", result: "Victoire", sflTime: true, buts: 1, passes: 4, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 1, player: "Kader", team: "Équipe B", statut: "Présent", result: "Défaite", sflTime: true, buts: 2, passes: 3, cleanSheet: false, mvp: true, impact: true, def: false, retard: false },
  { j: 1, player: "Yanis", team: "Équipe B", statut: "Présent", result: "Défaite", sflTime: true, buts: 2, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 1, player: "Adil", team: "Équipe B", statut: "Présent", result: "Défaite", sflTime: true, buts: 1, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 1, player: "Mehdi", team: "Équipe B", statut: "Présent", result: "Défaite", sflTime: true, buts: 1, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 1, player: "Sidali", team: "Équipe B", statut: "Présent", result: "Défaite", sflTime: true, buts: 2, passes: 2, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },

  { j: 2, player: "Adil", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 0, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Azzedine", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 2, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Ilies", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 4, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Ibrahim", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 1, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Kader", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 3, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Moussa", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 1, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Naim", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Ryad", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 0, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Sidali", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 0, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Smail", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 2, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Souley", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 2, passes: 3, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Wadie", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 0, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Yacine", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Yamin", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 1, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Yanis", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 2, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Zakary", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 6, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Anis", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 2, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Omar", team: null, statut: "Absent justifié", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 2, player: "Mehdi", team: null, statut: "Absent justifié", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },

  { j: 3, player: "Smail", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 2, cleanSheet: false, mvp: false, impact: true, def: false, retard: false },
  { j: 3, player: "Kylian", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 4, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 3, player: "Ibrahim", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 3, player: "Franz", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 1, passes: 0, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 3, player: "Ayman", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 3, player: "Wadie", team: null, statut: "Absent justifié", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 3, player: "Bilal", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 0, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 3, player: "Adrien", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 3, player: "Kader", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 3, player: "Ilyes", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 5, passes: 0, cleanSheet: false, mvp: true, impact: true, def: false, retard: false },
  { j: 3, player: "Moussa", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 1, passes: 2, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 3, player: "Adil", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 3, player: "Badis", team: "Vert", statut: "Absent justifié", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 3, player: "Zakary", team: "Vert", statut: "Présent", result: "Défaite", sflTime: false, buts: 2, passes: 4, cleanSheet: false, mvp: false, impact: true, def: false, retard: false },
  { j: 3, player: "Yacine", team: "Vert", statut: "Présent", result: "Défaite", sflTime: false, buts: 3, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 3, player: "Anis", team: "Vert", statut: "Présent", result: "Défaite", sflTime: false, buts: 2, passes: 0, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 3, player: "Naim", team: "Vert", statut: "Présent", result: "Défaite", sflTime: false, buts: 1, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 3, player: "Soffiane", team: null, statut: "Absent justifié", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 3, player: "Souley", team: "Jaune", statut: "Présent", result: "Victoire", sflTime: false, buts: 5, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 3, player: "Sidali", team: "Jaune", statut: "Absent justifié", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 3, player: "Ilies", team: "Jaune", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 5, cleanSheet: false, mvp: true, impact: true, def: false, retard: false },
  { j: 3, player: "Ryad", team: "Jaune", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 3, player: "Yamin", team: "Jaune", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 1, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 3, player: "Zakaria", team: "Jaune", statut: "Présent", result: "Victoire", sflTime: false, buts: 1, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },

  { j: 4, player: "Anis", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 3, passes: 6, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 4, player: "Ilies", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 6, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 4, player: "Bilal", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 6, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 4, player: "Adrien", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 0, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 4, player: "Ilyes", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 8, passes: 3, cleanSheet: false, mvp: true, impact: true, def: false, retard: false },
  { j: 4, player: "Badis", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 4, passes: 2, cleanSheet: false, mvp: false, impact: true, def: false, retard: false },
  { j: 4, player: "Yamin", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 3, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 4, player: "Ayman", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 4, player: "Kader", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 3, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 4, player: "Azzedine", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 1, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 4, player: "Wadie", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 1, passes: 5, cleanSheet: false, mvp: true, impact: true, def: true, retard: false },
  { j: 4, player: "Zakaria", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 4, player: "Mehdi", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 4, player: "Yanis", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 3, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 4, player: "Sidali", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 3, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 4, player: "Soffiane", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 2, passes: 0, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 4, player: "Adil", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 4, player: "Yacine", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 4, player: "Moussa", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 4, player: "Ryad", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 4, player: "Smail", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 3, passes: 0, cleanSheet: false, mvp: false, impact: true, def: false, retard: false },
  { j: 4, player: "Naim", team: null, statut: "Présent", result: "Nul", sflTime: false, buts: 1, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },

  { j: 5, player: "Badis", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 1, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 5, player: "Samy", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 1, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Ilies", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 2, cleanSheet: false, mvp: false, impact: true, def: false, retard: false },
  { j: 5, player: "Souley", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 3, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: true },
  { j: 5, player: "Selim laouadi", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 1, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Abdel", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 2, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Ibrahim", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Sidali", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 2, passes: 1, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 5, player: "Ilyes", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 3, passes: 2, cleanSheet: false, mvp: true, impact: true, def: false, retard: false },
  { j: 5, player: "Yacine", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 1, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Bilal", team: "Vert", statut: "Présent", result: "Défaite", sflTime: false, buts: 1, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Azzedine", team: "Vert", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Adil Maimouni", team: "Vert", statut: "Présent", result: "Défaite", sflTime: false, buts: 1, passes: 0, cleanSheet: false, mvp: false, impact: true, def: false, retard: false },
  { j: 5, player: "Ayman", team: "Vert", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Hassan Abdel", team: "Vert", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 5, player: "Mehdi", team: "Jaune", statut: "Présent", result: "Victoire", sflTime: false, buts: 3, passes: 4, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Jouneid", team: "Jaune", statut: "Présent", result: "Victoire", sflTime: false, buts: 6, passes: 2, cleanSheet: false, mvp: true, impact: true, def: false, retard: false },
  { j: 5, player: "Ryad", team: "Jaune", statut: "Présent", result: "Victoire", sflTime: false, buts: 1, passes: 3, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Yanis", team: "Jaune", statut: "Présent", result: "Victoire", sflTime: false, buts: 3, passes: 3, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Soffiane", team: "Jaune", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 3, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 5, player: "Anas", team: "Rouge", statut: "Présent", result: "Défaite", sflTime: false, buts: 1, passes: 2, cleanSheet: false, mvp: true, impact: true, def: true, retard: false },
  { j: 5, player: "Adrien", team: "Rouge", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Kais", team: "Rouge", statut: "Présent", result: "Défaite", sflTime: false, buts: 2, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Khadim", team: "Rouge", statut: "Suspendu", result: "Défaite", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Naim", team: "Rouge", statut: "Blessure", result: "Défaite", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Zakaria", team: "Gris", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Anis", team: "Gris", statut: "Présent", result: "Victoire", sflTime: false, buts: 1, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Kamil", team: "Gris", statut: "Présent", result: "Victoire", sflTime: false, buts: 3, passes: 2, cleanSheet: false, mvp: false, impact: true, def: false, retard: false },
  { j: 5, player: "Adil Zerhoui", team: "Gris", statut: "Présent", result: "Victoire", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 5, player: "Sosso Abdel", team: "Gris", statut: "Présent", result: "Victoire", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },

  { j: 6, player: "Ilyes", team: "Orange", statut: "Présent", result: "Défaite", sflTime: false, buts: 3, passes: 1, cleanSheet: false, mvp: false, impact: true, def: false, retard: false },
  { j: 6, player: "Sofiane", team: "Orange", statut: "Présent", result: "Défaite", sflTime: false, buts: 1, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 6, player: "Yamin", team: "Orange", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 6, player: "Yanis", team: "Orange", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 6, player: "Sosso Abdel", team: "Orange", statut: "Présent", result: "Défaite", sflTime: false, buts: 1, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 6, player: "Sidali", team: "Bleu", statut: "Présent", result: "Victoire", sflTime: false, buts: 3, passes: 3, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 6, player: "Jouneid", team: "Bleu", statut: "Présent", result: "Victoire", sflTime: false, buts: 4, passes: 4, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 6, player: "Anis", team: "Bleu", statut: "Présent", result: "Victoire", sflTime: false, buts: 5, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 6, player: "K2R", team: "Bleu", statut: "Présent", result: "Victoire", sflTime: false, buts: 1, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 6, player: "Sosso Coach", team: "Bleu", statut: "Présent", result: "Victoire", sflTime: false, buts: 1, passes: 1, cleanSheet: false, mvp: true, impact: true, def: false, retard: false },
  { j: 6, player: "Gaïl", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 1, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 6, player: "Yacine Ben", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 6, player: "Adil Maimouni", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 1, passes: 2, cleanSheet: false, mvp: false, impact: true, def: false, retard: false },
  { j: 6, player: "Souley", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 5, passes: 4, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 6, player: "Ryad", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 6, player: "Ibrahim", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 6, player: "Naim", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 1, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 6, player: "Kader", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 1, passes: 2, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 6, player: "Mehdi", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 6, player: "Bilal", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 6, player: "Zakaria", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 1, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 6, player: "Selim laouadi", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 4, passes: 2, cleanSheet: false, mvp: true, impact: true, def: false, retard: false },

  { j: 7, player: "Ilyes", team: "Orange", statut: "Présent", result: "Défaite", sflTime: false, buts: 3, passes: 2, cleanSheet: false, mvp: false, impact: true, def: false, retard: false },
  { j: 7, player: "Sidali", team: "Orange", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 7, player: "Sofiane", team: "Orange", statut: "Présent", result: "Défaite", sflTime: false, buts: 3, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 7, player: "Lyes Korogli", team: "Orange", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 7, player: "Zakary", team: "Orange", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 7, player: "Naim", team: "Orange", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 7, player: "Ilies", team: "Bleu", statut: "Présent", result: "Victoire", sflTime: false, buts: 4, passes: 3, cleanSheet: false, mvp: true, impact: true, def: false, retard: false },
  { j: 7, player: "Anis", team: "Bleu", statut: "Présent", result: "Victoire", sflTime: false, buts: 8, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 7, player: "Henri", team: "Bleu", statut: "Présent", result: "Victoire", sflTime: false, buts: 7, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 7, player: "Sosso Coach", team: "Bleu", statut: "Présent", result: "Victoire", sflTime: false, buts: 1, passes: 4, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 7, player: "Moussa", team: "Bleu", statut: "Présent", result: "Victoire", sflTime: false, buts: 0, passes: 6, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 7, player: "Soffiane", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 1, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 7, player: "Selim laouadi", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 4, passes: 2, cleanSheet: false, mvp: false, impact: true, def: false, retard: false },
  { j: 7, player: "Aghiless", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 1, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 7, player: "Adil Maimouni", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 4, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 7, player: "Mehdi", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 3, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 7, player: "Yazid", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 1, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 7, player: "Adrien", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 1, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 7, player: "Zakaria", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 4, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 7, player: "Ibrahim", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 1, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 7, player: "Abdel", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 7, passes: 2, cleanSheet: false, mvp: true, impact: true, def: false, retard: false },
  { j: 7, player: "Gaïl", team: "Rouge", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 2, cleanSheet: false, mvp: true, impact: true, def: false, retard: false },
  { j: 7, player: "Adil Zerhoui", team: "Rouge", statut: "Présent", result: "Victoire", sflTime: false, buts: 1, passes: 1, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 7, player: "Giovani", team: "Gris", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 7, player: "Malik", team: "Gris", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 1, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 7, player: "illiasse", team: "Gris", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 7, player: "Yacine Ben", team: "Gris", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 7, player: "kevin Raes", team: "Gris", statut: "Présent", result: "Défaite", sflTime: false, buts: 2, passes: 1, cleanSheet: false, mvp: false, impact: true, def: false, retard: false },
  { j: 7, player: "Giovani", team: "Gris", statut: "Présent", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false, note: "Extra time", teamScoreBonus: 2, extraTime: true },
  { j: 7, player: "Gaïl", team: "Rouge", statut: "Présent", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false, note: "Extra time", teamScoreBonus: 5, extraTime: true },
  { j: 7, player: "Naim", team: null, statut: "Présent", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false, note: "Bonus extra time", pepiteBonus: 7, extraTime: true },
  { j: 7, player: "Smail", team: null, statut: "Présent", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false, note: "Bonus extra time", pepiteBonus: 7, extraTime: true },
  { j: 7, player: "Adil", team: null, statut: "Présent", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false, note: "Bonus extra time", pepiteBonus: 4, extraTime: true },
  { j: 7, player: "Kader", team: null, statut: "Présent", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false, note: "Bonus extra time", pepiteBonus: 7, extraTime: true },
  { j: 7, player: "Sidali", team: null, statut: "Présent", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false, note: "Bonus extra time", pepiteBonus: 4, extraTime: true },
  { j: 7, player: "Ilies", team: null, statut: "Présent", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false, note: "Bonus extra time", pepiteBonus: 2, extraTime: true },
  { j: 7, player: "Ilyes", team: null, statut: "Présent", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false, note: "Bonus extra time", pepiteBonus: 2, extraTime: true },
  { j: 7, player: "Ibrahim", team: null, statut: "Présent", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false, note: "Bonus extra time", pepiteBonus: 2, extraTime: true },
  { j: 7, player: "Ryad", team: null, statut: "Présent", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false, note: "Bonus extra time", pepiteBonus: 1, extraTime: true },
  { j: 7, player: "Bilal", team: null, statut: "Présent", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false, note: "Bonus extra time", pepiteBonus: 1, extraTime: true },
  { j: 7, player: "Adil Maimouni", team: null, statut: "Présent", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false, note: "Bonus extra time", pepiteBonus: 1, extraTime: true },
  { j: 7, player: "Yacine", team: null, statut: "Présent", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false, note: "Bonus extra time", pepiteBonus: 1, extraTime: true },
  { j: 7, player: "Sosso Coach", team: null, statut: "Présent", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false, note: "Bonus extra time", pepiteBonus: 1, extraTime: true },
  { j: 7, player: "Anis", team: null, statut: "Présent", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false, note: "Bonus extra time", pepiteBonus: 1, extraTime: true },
  { j: 7, player: "Anas", team: null, statut: "Présent", result: null, sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false, note: "Bonus extra time", pepiteBonus: 1, extraTime: true },

  { j: 8, player: "Ilyes", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 4, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 8, player: "Anis", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 4, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 8, player: "Isma", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 4, passes: 0, cleanSheet: false, mvp: false, impact: true, def: true, retard: false },
  { j: 8, player: "Yamin", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 8, player: "Zakaria", team: "Orange", statut: "Présent", result: "Victoire", sflTime: false, buts: 2, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 8, player: "Ilies", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 1, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 8, player: "Franz", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 4, passes: 1, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 8, player: "Sosso Coach", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 5, passes: 3, cleanSheet: false, mvp: true, impact: true, def: false, retard: false },
  { j: 8, player: "Henri", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 8, player: "Sidali", team: "Bleu", statut: "Présent", result: "Défaite", sflTime: false, buts: 2, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 8, player: "Anas", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 4, passes: 4, cleanSheet: false, mvp: true, impact: true, def: false, retard: false },
  { j: 8, player: "Ibrahim", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 0, passes: 2, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 8, player: "Yassir", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 1, passes: 1, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 8, player: "Adrien", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 3, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 8, player: "Kais", team: "Vert", statut: "Présent", result: "Victoire", sflTime: false, buts: 3, passes: 1, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 8, player: "Kamil", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 1, passes: 1, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
  { j: 8, player: "Yacine Ben", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 1, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 8, player: "Gaïl", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 3, passes: 1, cleanSheet: false, mvp: false, impact: true, def: false, retard: false },
  { j: 8, player: "Ryad", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: false, retard: false },
  { j: 8, player: "Kader", team: "Jaune", statut: "Présent", result: "Défaite", sflTime: false, buts: 0, passes: 0, cleanSheet: false, mvp: false, impact: false, def: true, retard: false },
];
